// Generated by https://quicktype.io

import { Classificacao } from "./classificacao";
import { ContaBancaria } from "./conta-bancaria";
import { Devedor } from "./devedor";
import { Entrada } from "./entrada";

export interface ItemListaEntradaApi {
    id: number;
    dataPrevistaRecebimento: string;
    dataRecebimento: string | null;
    valor: number;
    valorRecebido: number | null;
    classificacao: Classificacao;
    entrada: Entrada;
    conta: ContaBancaria | null;
    situacao: string;
    devedor: Devedor;
}